spring.application.name=spring-ai-examples
logging.level.org.zalando.logbook=TRACE
logbook.format.style=http
spring.ai.openai.chat.options.temperature=1
#spring.ai.openai.chat.options.top-p=0.8 # Top-P has a range of 0 to 1 and is used to limit the set of candidate tokens to the smallest set where the sum of probabilities meets or exceeds the value of top-P
#spring.ai.ollama.chat.options.top-k=4 #open ai dose not support this
